// USER LOGIN, REGISTER, LOADING
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// ERRORS & SUCCESS GETTER AND CLEARERS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

// EMAIL CONFIRMATION
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const CONFIRMATION_FAIL = 'CONFIRMATION_FAIL';

// FORGOT & RESET PASSWORD
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// DASHBOARD
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED';

// DOGS
export const GET_DOGS = 'GET_DOGS';
export const ADD_DOG = 'ADD_DOG';
export const ADD_DOG_SUCCESS = 'ADD_DOG_SUCCESS'; //Remove
export const ADD_DOG_FAIL = 'ADD_DOG_FAIL';
export const DELETE_DOG = 'DELETE_DOG';
export const DOGS_LOADING = 'DOGS_LOADING';
export const DOGS_LOADING_FAIL = 'DOGS_LOADING_FAIL';

// FAMILY
export const REGISTER_FAMILY_SUCCESS = 'REGISTER_FAMILY_SUCCESS';
export const REGISTER_FAMILY_FAIL = 'REGISTER_FAMILY_FAIL';
export const LEAVE_FAMILY_SUCCESS = 'LEAVE_FAMILY_SUCCESS';
export const LEAVE_FAMILY_FAIL = 'LEAVE_FAMILY_FAIL';
export const INVITE_TO_FAMILY_SUCCESS = 'INVITE_TO_FAMILY_SUCCESS';
export const INVITE_TO_FAMILY_FAIL = 'INVITE_TO_FAMILY_FAIL';
export const HAS_FAMILY = 'HAS_FAMILY';
export const FAMILY_JOIN_SUCCESS = 'FAMILY_JOIN_SUCCESS';
export const FAMILY_JOIN_FAIL = 'FAMILY_JOIN_FAIL';

// WALKS
export const WALKS_LOADING = 'WALKS_LOADING';
export const INITIAL_WALKS = 'INITIAL_WALKS';
export const ADD_WALK = 'ADD_WALK';
export const ADD_WALK_FAIL = 'ADD_WALK_FAIL';
export const DELETE_WALK = 'DELETE_WALK';
export const DELETE_WALK_FAIL = 'DELETE_WALK_FAIL';
